---
templateVersion: '2020-01-25'
componentName: aws.greengrass.mqtt
description: AWS Greengrass MQTT Broker
publisher: AWS
version: '0.0.0'
componentType: plugin
manifests:
  - platform:
      os: all
      architecture: all
    artifacts:
      - uri: s3://gg-dev-artifacts/$componentName/$platform.os/$version/aws.greengrass.mqtt.jar
