---
RecipeFormatVersion: '2020-01-25'
ComponentName: aws.greengrass.clientdevices.mqtt.Moquette
ComponentDescription: AWS Greengrass MQTT
ComponentPublisher: AWS
ComponentVersion: 0.0.0
ComponentType: aws.greengrass.plugin
Manifests:
  - Artifacts:
      - URI: s3://gg-dev-artifacts-$stage/$componentName/$version/aws.greengrass.clientdevices.mqtt.Moquette.jar
    Dependencies:
        aws.greengrass.clientdevices.Auth:
            VersionRequirement: '>=0.0.0'
            DependencyType: HARD
